spring:
  servlet.multipart:
    max-file-size: 2MB
    max-request-size: 2MB

application:
  upload-directory: sample
  secret-key: booksplitting-secret-key
  security-provider: BC
  file-crypto-algorithm:
    name: MD5
    content: AES/ECB/PKCS7Padding
    key: AES